REPLICATE1_NAME: 'replicate1' 
REPLICATE2_NAME: 'replicate2' 
REPLICATE1: ['SLX-19014.ATACAd001.HYTFKDRXX.s_1','SLX-19014.ATACAd004.HYTFKDRXX.s_1','SLX-19014.ATACAd006.HYTFKDRXX.s_1','SLX-19014.ATACAd008.HYTFKDRXX.s_1']
REPLICATE2: ['SLX-19014.ATACAd003.HYTFKDRXX.s_1','SLX-19014.ATACAd005.HYTFKDRXX.s_1','SLX-19014.ATACAd007.HYTFKDRXX.s_1','SLX-19014.ATACAd009.HYTFKDRXX.s_1']

WORKDIR: '/rds/project/yhbl2/rds-yhbl2-genehunter/SM/ATAC-Seq'
CHR : 'chrM'
GENOME: "/rds/project/yhbl2/rds-yhbl2-genehunter/SM/annotations/Mus_musculus/Ensembl/GRCm38/Sequence/Bowtie2Index/genome"
INDEX: "/rds/project/yhbl2/rds-yhbl2-genehunter/SM/annotations/Mus_musculus/Ensembl/GRCm38/Sequence/Bowtie2Index/genome"


LEN : 50
QV: 0.01
AUC: 500
