REPLICATE1_NAME: 'replicate1' 
REPLICATE2_NAME: 'replicate2' 

REPLICATE1: "replicate1.tsv"
REPLICATE2: "replicate2.tsv"

PAIRED: TRUE #Use False for Single-end reads
CHR : 'chrM'
GENOME: "/rds/project/yhbl2/rds-yhbl2-genehunter/SM/annotations/Mus_musculus/Ensembl/GRCm38/Sequence/Bowtie2Index/genome"
INDEX: "/rds/project/yhbl2/rds-yhbl2-genehunter/SM/annotations/Mus_musculus/Ensembl/GRCm38/Sequence/Bowtie2Index/genome"


LEN : 100
QV: 0.01
AUC: 500
