# conda environment configuration for snakemake
name: SV 
channels:
    - bioconda
    - conda-forge
    - dranew
    - defaults
dependencies:
    - trim-galore=0.6.6
    - bowtie2=2.3.5.1
    - genrich=0.6.1
    - bedtools=2.30.0
    - samtools=1.11
